"""Initial database schema

Revision ID: 4f0dfaed07e3
Revises: a1b2408a73ed
Create Date: 2025-12-18 04:53:34.383929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0dfaed07e3'
down_revision: Union[str, None] = 'a1b2408a73ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
